### ISSUE TITLE
@testWith annotation not working with PHPUnit 9.5 + PHP 8

### ISSUE THREAD

**Issue by oconnedk** [Codeception/Codeception#6575]
#### What are you trying to achieve?

Use `@testWith` annotations in unit tests.

#### What do you get instead?

`Too few arguments to function`

> Console output

```bash
./vendor/bin/codecept run tests/Unit/Codeception/SomethingTest.php -vvv
Codeception PHP Testing Framework v5.0.2 https://helpukrainewin.org

Tests.Unit Tests (1) ------------------------------------------------------------------------------------------------------------
Modules: Asserts
---------------------------------------------------------------------------------------------------------------------------------
E SomethingTest: Something (0.01s)
---------------------------------------------------------------------------------------------------------------------------------
Time: 00:00.056, Memory: 8.00 MB

There was 1 error:
1) SomethingTest: Something
   Test  tests/Unit/Codeception/SomethingTest.php:testSomething

[ArgumentCountError] Too few arguments to function Tests\Codeception\SomethingTest::testSomething(), 0 passed in /tmp/phpunit-test/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1545 and exactly 1 expected

/tmp/phpunit-test/tests/Unit/Codeception/SomethingTest.php:10
/tmp/phpunit-test/vendor/phpunit/phpunit/src/Framework/TestCase.php:1545
/tmp/phpunit-test/vendor/phpunit/phpunit/src/Framework/TestCase.php:1151
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Test/TestCaseWrapper.php:142
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Test/Test.php:170
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Suite.php:130
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/SuiteManager.php:148
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Codecept.php:260
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Codecept.php:216
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Command/Run.php:437
/tmp/phpunit-test/vendor/symfony/console/Command/Command.php:308
/tmp/phpunit-test/vendor/symfony/console/Application.php:1002
/tmp/phpunit-test/vendor/symfony/console/Application.php:299
/tmp/phpunit-test/vendor/symfony/console/Application.php:171
/tmp/phpunit-test/vendor/codeception/codeception/src/Codeception/Application.php:112
/tmp/phpunit-test/vendor/codeception/codeception/app.php:45
/tmp/phpunit-test/vendor/codeception/codeception/app.php:46
/tmp/phpunit-test/vendor/codeception/codeception/codecept:7
/tmp/phpunit-test/vendor/bin/codecept:120


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

> Test source code if related

#### composer.json
```json
{
    "name": "root/phpunit-test",
    "autoload": {
        "psr-4": {
            "Root\\PhpunitTest\\": "src/"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^9.0",
        "codeception/codeception": "^5.0",
        "codeception/module-asserts": "^3.0"
    }
}
```
#### tests/Unit/Codeception/SomethingTest.php
```php
<?php
namespace Tests\Codeception;

class SomethingTest extends \Codeception\Test\Unit
{
    /**
     * @param $value
     * @testWith ["a" ]
     */
    public function testSomething($value)
    {
    }
}
```
### Details

* Codeception version: 5.0.2
* PHP Version: 8.1.10
* Operating System: Ubuntu 18.04.6 LTS
* Installation type: Composer
* List of installed packages (`composer show`)
```
behat/gherkin                      v4.9.0  Gherkin DSL parser for PHP
codeception/codeception            5.0.2   BDD-style testing framework
codeception/lib-asserts            2.0.0   Assertion methods used by Codeception core and Asserts module
codeception/module-asserts         3.0.0   Codeception module containing various assertions
codeception/stub                   4.0.2   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.4.1   A small, lightweight utility to instantiate objects in PHP without invoking their...
myclabs/deep-copy                  1.11.0  Create deep copies (clones) of your objects
nikic/php-parser                   v4.15.1 A PHP parser written in PHP
phar-io/manifest                   2.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.2.1   Library for handling version information and constraints
phpunit/php-code-coverage          9.2.17  Library that provides collection, processing, and rendering functionality for PHP...
phpunit/php-file-iterator          3.0.6   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.5.24  The PHP Unit Testing framework.
psr/container                      2.0.2   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher               1.0.0   Standard interfaces for event handling.
psy/psysh                          v0.11.8 An interactive shell for modern PHP.
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.8   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4   Diff implementation
sebastian/environment              5.1.4   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.5   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.5   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     3.2.0   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
symfony/console                    v6.1.4  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.1.3  Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v3.1.1  A generic function and convention to trigger deprecation notices
symfony/event-dispatcher           v6.1.0  Provides tools that allow your application components to communicate with each ot...
symfony/event-dispatcher-contracts v3.1.1  Generic abstractions related to dispatching event
symfony/finder                     v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/polyfill-ctype             v1.26.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer   v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 Symfony polyfill for the Mbstring extension
symfony/service-contracts          v3.1.1  Generic abstractions related to writing services
symfony/string                     v6.1.4  Provides an object-oriented API to strings and deals with bytes, UTF-8 code point...
symfony/var-dumper                 v6.1.3  Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                       v6.1.4  Loads and dumps YAML files
theseer/tokenizer                  1.2.1   A small library for converting tokenized PHP source code into XML and potentially...
```
* Suite configuration:

```yml
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
### Test with PHPUnit 9

Using the above `composer` file and configuration, an identical test extending `PHPUnit\Framework\TestCase` works fine:

```bash
./vendor/bin/phpunit tests/Unit/PHPUnit/SomethingTest.php
PHPUnit 9.5.24 #StandWithUkraine

R                                                                   1 / 1 (100%)

Time: 00:00.013, Memory: 4.00 MB

There was 1 risky test:

1) Tests\PHPUnit\SomethingTest::testSomething with data set #0 ('a')
   This test did not perform any assertions

/tmp/phpunit-test/tests/Unit/PHPUnit/SomethingTest.php:12

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 1.
```

**Comment by Naktibalda** [comment]
Not supported since https://github.com/Codeception/Codeception/pull/6491

You could use Codeception example annotation instead  `@example ['a']`, or implement support for `@testwith` in https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Test/DataProvider.php yourself and raise pull request.

PhpUnit 10 `#[PHPUnit\Framework\Attributes\TestWith]`attribute won't be supported.

**Comment by oconnedk** [comment]
OK, thanks. I couldn't find anything mentioning it, but suspected as much.
I can update the documentation if you can point me to the right place - will prevent further issues like this?
Thanks again.

**Comment by oconnedk** [comment]
Thanks again, @Naktibalda , `@example` works perfectly as a kind-of drop-in replacement!

For others facing a similar issue, wishing to migrate from `@testWith`, I amended my `SomethingTest` from above as follows, and it worked perfectly:
```php
<?php
namespace Tests\Codeception;

class SomethingTest extends \Codeception\Test\Unit
{
    /**
     * @param $value
     * @example ["a"]
     * @example [["this", "is", "an", "array"]]
     * @example [{"associative": "array"}]
     */
    public function testSomething($value)
    {
    }
}
```

**Note**: `@example` is needed on a line-by-line basis (whereas `@testWith` would allow multiple rows with just one `@testWith` annotation.
